config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: :index
  get 'user/matsuoka' => 'users#matsuoka'
  get 'user/tatsuya' => 'users#tatsuya'
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all.order(created_at: :asc)
	end

	def tatsuya
		@user = User.find_by(id: 1)
		@user.passion += 1
		@user.save
		redirect_to users_path
	end

	def matsuoka
		@user = User.find_by(id: 2)
		@user.passion += 1
		@user.save
		redirect_to users_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PassionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<div class="factor">
		<div class="name"><%= user.name %></div>
		<div class="image"><%= image_tag "/assets/#{user.image}", :size =>'200x200' %></div>
		<div class="passion"><%= " 情熱ポイント#{user.passion}" %></div>
		<% if user.name=="tatsuya" %>
			<%= link_to "Tatsuya", user_tatsuya_path %>
		<% elsif user.name=="matsuoka" %>
			<%= link_to "Matsuoka", user_matsuoka_path %>
		<% end %>
	</div>
<% end %>
<div class="discription">これはTatsuyaのLife is techに対する情熱と、松岡修造の情熱をポイントとして可視化したアプリケーションです。</div>
<div class="sab-discription">ボタンを押すと情熱を追加できます。(現在のポイントはTatsuyaと松岡修造が実際に情熱をクリックしたとかどうとか。。。)</div>